### ISSUE TITLE
Extension breaks Flarum

### ISSUE THREAD

**Issue by tituspijean** [tituspijean/flarum-ext-auth-ssowat#10]
PHP fatal error upon extension activation. I cannot find out what in the code makes it happen.

```
2018/02/13 21:21:26 [error] 18447#0: *528 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Output has been emitted pr$
Stack trace:
#0 /var/www/flarum/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php(27): Zend\Diactoros\Response\SapiEmitter->assertNoPreviousOutput()
#1 /var/www/flarum/vendor/zendframework/zend-diactoros/src/Server.php(162): Zend\Diactoros\Response\SapiEmitter->emit(Object(Zend\Diactoros\Response))
#2 /var/www/flarum/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\Diactoros\Server->listen(Object(Zend\Stratigility\NoopFinalHandler))
#3 /var/www/flarum/index.php(16): Flarum\Http\AbstractServer->listen()
```

**Comment by luceos** [comment]
This error signifies that something already outputted an error. Without that original error there's no way you'll be able to solve the issue.

Please note the Flarum codebase is not causing this issue, most likely your PHP is misconfigured and missing a dependency or running into a constraint that the code cannot lift by itself.

**Comment by tituspijean** [comment]
Got it. Namespaces issues, update to follow.
